### ISSUE TITLE
Add MRCC ID and Functional Class (from MRCC network) to default network export

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/Lasso#102]

**Comment by DavidOry** [comment]
@i-am-sijia 
Rachel asked the we put the mrcc_id back into the network. Do we have a lookup connecting the shst ID to the mrcc id? I do not see it in the data dir.

**Comment by DavidOry** [comment]
Okay. I think I understand what's going on. We should be able to rename the `source_link_id` to `mrcc_id` and then return it [here](https://github.com/wsp-sag/Lasso/blob/c292e24d59f8ed5cc5cfe4283f93d6aece88b0ae/lasso/roadway.py#L1254). Does that seem right to you @i-am-sijia?

**Comment by i-am-sijia** [comment]
Yep, that's right, I'm making the changes.
