### ISSUE TITLE
[BUG] fails to create roadway project card when a link gets added then edited

### ISSUE THREAD

**Issue by i-am-sijia** [wsp-sag/Lasso#131]
## Describe the bug
From Rachel:

> The simple log files that just add a link or node are working. But when I create a more complicated card that include Change on links, I can not get it to recognize  model_link_ids 
>  
> I have redone this card many times and can not get this to run.
> I tried setting the model_link_ids in cube, I tried setting them in the log file after. Neither was successful. 
>  
> See attached card: 
>  
> Added two new nodes. 
> Created three two-way links to connect nodes and existing system. 
> Added model link ids to new links 
> Set all links to drive = 1 
> Save log file

### Triggering line of code
![image](https://user-images.githubusercontent.com/28812722/154776860-0f1566aa-339c-41b7-bd00-5cbf1ea03ec2.png)

### Thoughts on resolution
It failed when Lasso is doing compatibility check on the logfile and the network.  There is a step in Lasso that checks each record with operation code = `C` in the logfile, to see if it exists in the base network.  If not, then error.

For the 'C' records in logfile that actually operates on newly added links and nodes, we should exclude them from compatibility checks.

**Comment by RachelWikenMC** [comment]
This is working for me now
