### ISSUE TITLE
Flesh out calculate_assignment_group() in roadway.py

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/Lasso#27]

**Comment by e-lo** [comment]
@i-am-sijia  - I am reviewing this and two things I can't figure out:

1. I think the github account is missing `*.mrcc.out.matched.geojson` is the file too big? if so, does it make sense to just have it as a csv of the shst id ?

2. I can't seem to find some of the methods mentioned in this class method, specifically: `ModelRoadwayNetwork.read_match_result()` as `well as get_attribute()`  where are they?

**Comment by e-lo** [comment]
never mind on #2 :-)

**Comment by e-lo** [comment]
Hmmm- this method still isn't making much sense to me. Do you have to walk thru it with me so I can understand your approach?

**Comment by i-am-sijia** [comment]
Sure, can you join the GoToMeeting we used last Tuesday?
