### ISSUE TITLE
Remove any hard-coded paths

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/Lasso#39]
i.e. `Z:/Sijia...`   :-)

**Comment by e-lo** [comment]
@i-am-sijia  i think there is just one left in `transit.py`: 
```python
bus_routetype_gdf = gpd.read_file(
            "Z:/Data/Users/Sijia/Met_Council/GIS/shp_trans_transit_routes/TransitRoutes.shp"
        )
```

**Comment by i-am-sijia** [comment]
moved that file to parameter, commit [ae08494](https://github.com/wsp-sag/Lasso/commit/ae0849474d785c33677f3bb7edce550e0e9139ee)

I guess we can remove this chunk:

https://github.com/wsp-sag/Lasso/blob/ae0849474d785c33677f3bb7edce550e0e9139ee/lasso/transit.py#L63-L66

**Comment by e-lo** [comment]
I actually updated how cube modes are calculated to be based on the route id and name:

I think this is a pretty good approximation and that way we don't need an extraneous shape file.

https://github.com/wsp-sag/Lasso/blob/47499c386cb8ba2862aaa9acffd509cbd94cfad0/lasso/transit.py#L1016-L1065
