### ISSUE TITLE
Replace simpleparse as a dependency

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/Lasso#44]
1. it is hard to install on windows
2. it hasn't been updated since (seemingly) 2010
3. we just ported it from original sfcta network wrangler

I'm sure we can do better in 2019...

**Comment by e-lo** [comment]
@i-am-sijia can you confirm that the package `lark-parser` is easily installed on windows?

**Comment by i-am-sijia** [comment]
installed successfully with `pip install lark-parser`, imported successfully with `from lark import Lark`

**Comment by e-lo** [comment]
Completed. New dependency is [`lark-parser`](https://github.com/lark-parser/lark) which has an active developer base
