### ISSUE TITLE
Add ability to concatenate log files

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/Lasso#54]

**Comment by e-lo** [comment]
Per discussion with @RachelWikenMC today, it sounds like Cube will save totality of changes each time you save the log so this is no longer necessary.

**Comment by JonathanEhrlichMC** [comment]
What is Cube crashes during an editing session. Would this ability help?
(Or is it better to restart the log file from the beginning of the edit?)

**Comment by RachelWikenMC** [comment]
As I start looking at making corrections to the network, we need ability to combine log files into one project card. There are some issues that are large enough that it is not possible to complete edits in one session
