### ISSUE TITLE
Lasso Scenario Creation Quickstart

### ISSUE THREAD

**Issue by jhelsel11** [wsp-sag/Lasso#59]
@e-lo, I tried to run Lasso Scenario Creation Quickstart.pynb. I received several errors related to the schema (e..g outboundReferenceIds, inboundReferenceIds). I think the schema that's on master might be out of date?

Would you take a look at the example notebooks and see if you also have problems running them? (If not, maybe it's something in the way I set up the repo?)

**Comment by i-am-sijia** [comment]
@e-lo @kulshresthaa 

Network Wrangler schema needs to be updated to the latest network.

node.geojson:

- `outboundReferenceIds` not `outboundReferenceId`

- `inboundReferenceIds` not `inboundReferenceId`


shape.geojson:

- `fromIntersectionId` not `shstFromIntersectionId`

- `toIntersectionId` not `shstToIntersectionId`

**Comment by jhelsel11** [comment]
@i-am-sijia or @e-lo, I would like to run lasso in a notebook that is not stored as a subfolder of the lasso directory. When I do, it throws an error in get_base_dir
` "Cannot find Lasso base directory from {}, please input using keyword in parameters: \`lasso_dir =\` ".format(init_d)`

I understand that I need to pass the directory for lasso in and that not doing so is causing the error. However, I'm unclear how to declare a kwarg that you pass in during an import statement (since it fails when I import Project from lasso. (The articles I found on kwargs all touched on using kwargs for a function but not this step.)

**Comment by e-lo** [comment]
> Network Wrangler schema needs to be updated to the latest network.

--> now fixed in Wrangler Develop branch : https://github.com/wsp-sag/network_wrangler/commit/7167f54351267b0af8cce06bfe7c404f5c5fd0d9

**Comment by e-lo** [comment]
> "Cannot find Lasso base directory from {}, please input using keyword in parameters:lasso_dir = \".format(init_d)

--> moving this to a separate issue
