### ISSUE TITLE
Add ML Lanes Logfile Example

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/Lasso#64]

**Comment by jhelsel11** [comment]
I don't have the ability to push to the repo. But I've attached the file here.
[pretend_managed_lanes.LOG](https://github.com/wsp-sag/Lasso/files/4321446/pretend_managed_lanes.LOG)

**Comment by e-lo** [comment]
@jhelsel11  -  is this built on the current base network that is in Network Wrangler? I couldn't find node 49003, etc.

```python
ERROR    WranglerLogger:project.py:334 Network missing the following AB links:
                                              A      B model_link_id
                                       0  36237  49003           NaN
                                       1  49003  35399           NaN
                                       2  35399  36265           NaN
                                       3  36265  36263           NaN
                                       4  36263  38844           NaN
```

**Comment by jhelsel11** [comment]
I will confirm, but I believe so. I was using the old trueshape file during the editing, but I don't think that should be a problem.

**Comment by e-lo** [comment]
Can you double-check?

**Comment by jhelsel11** [comment]
I just pushed a commit to the develop branch where I definitively redid the log file. I used the network Sijia exported to fixed width on 2/28.

**Comment by i-am-sijia** [comment]
@e-lo @jhelsel11, node 49003 is outside of the stpaul boundary file I used to clip network, thus that link is not part of the stpaul network, same for the others.

**Comment by jhelsel11** [comment]
I see. The log file was meant to be an example of a real managed lane. It is the portion of the I394E managed lane that runs parallel to the main lane (instead of being a switchable 2 lanes in the middle). Sorry for the confusion.

**Comment by i-am-sijia** [comment]
@e-lo  Question: Do we need to have `ML_lanes` and `segment_id` in link.json?

**Comment by e-lo** [comment]
> Question: Do we need to have ML_lanes and segment_id in link.json?

Since we know MetCouncil uses both of them, yes please.

**Comment by e-lo** [comment]
>The log file was meant to be an example of a real managed lane. It is the portion of the I394E managed > lane that runs parallel to the main lane (instead of being a switchable 2 lanes in the middle). Sorry for > the confusion.

I don't think it *needs* to be "real" per se.

**Comment by i-am-sijia** [comment]
I will not add ML_lanes and segment_id to link.json.  They will be in fixed width files and default to 0, Lasso will use ML LOG file to generate ML project card for network wrangler, and update them in fixed width files.
