### ISSUE TITLE
create_managed_lane_network() in network wrangler adds problematic link records

### ISSUE THREAD

**Issue by jhelsel11** [wsp-sag/Lasso#66]
Cube requires A and B to be integers, not characters, but they are currently written as characters in make_complete_network_from_fixed_width_file.s (see example below with file extension changed so it can be uploaded to github). I'm working around this for now by manually changing the .s file. 

[make_complete_network_from_fixed_width_file.txt](https://github.com/wsp-sag/Lasso/files/4389782/make_complete_network_from_fixed_width_file.txt)

**Comment by jhelsel11** [comment]
drive_access should also be numeric.

**Comment by i-am-sijia** [comment]
They are written out as numeric on my end.   That's weird, I need to take a look at Lasso.

**Comment by jhelsel11** [comment]
Sijia, you should be able to access the notebook I was working with here: https://github.com/wsp-sag/Lasso/blob/develop/notebooks/Broken%20Parallel%20Managed%20Lanes.ipynb.

You may need to update a few file paths.

**Comment by i-am-sijia** [comment]
Ok, found where things go wrong.  There's some issue with method [`create_managed_lane_network()`](https://github.com/wsp-sag/network_wrangler/blob/4fae96b0ee9785639587ceae2fe196c727097e3d/network_wrangler/RoadwayNetwork.py#L1656), which sits in Network Wrangler but operates on Lasso network object when writing out Metcouncil format.

After applying this method, in the example, there are 15 link records created.   See below for 15 links created by this method.  I think the first 5 are probably valid, given the project card having 5 ML changes, but the other 10 links having A node equal to B node looks problematic to me.  And adding these 15 links are messing up the data type.

@e-lo  can you take a look?  I'll try look at this tomorrow as well.

![image](https://user-images.githubusercontent.com/28812722/77718076-5c371200-6fb8-11ea-9ec6-ffe1188f6c62.png)

**Comment by kulshresthaa** [comment]
@i-am-sijia Can you point me to the managed lane project card that is being applied here? The other 10 links are dummy connectors links (access/egress) and those should have different A and B node. I will debug why they are coming out same!

**Comment by i-am-sijia** [comment]
It's the [broken_parallel_managed_lane.yml](https://github.com/wsp-sag/network_wrangler/blob/develop/examples/stpaul/project_cards/broken_parallel_managed_lane.yml) that John manually created for testing purpose.

**Comment by kulshresthaa** [comment]
@i-am-sijia the bug is fixed in wrangler. You should now see different A and B node for those connector links.

**Comment by i-am-sijia** [comment]
@kulshresthaa thanks that worked.

@jhelsel11 I made more changes in Lasso to make sure variable types are correct after applying ML projects.  The pipeline worked in the latest notebook, please test and circle back.

**Comment by jhelsel11** [comment]
@i-am-sijia that works.
