### ISSUE TITLE
Fixed width file needs to tell user which link is the general purpose lane and which is the managed lane.

### ISSUE THREAD

**Issue by jhelsel11** [wsp-sag/Lasso#67]
Will you take a look at the results of roadway_standard_to_met_council network in the Broken Parallel Managed Lanes notebook? Specifically, look at link 390975, which is one of the links that is being transformed as a managed lane. 
After the function is run, the attribute ML_lanes (and all time periods is set to 0) and HOV = 5. The corresponding link that is created 1390975 has ML_lanes = 0 and HOV = 5. Thus, there is no easy way to know the correspondence between the two, unless the user goes into network wrangler and looks up the value of the scalar used to create a managed lane from a normal lane.

Would it be possible to have the parallel managed lane that is create have a value of 1 for ML_lanes (and/or the specific time period the managed lane is active for) and the HOV to also be set to 5? That would make it much easier to set up the filters inside of Cube.

**Comment by jhelsel11** [comment]
If that is not possible, I can set up a work around within cube, but it will rely on the value of the scalar being fixed and will fix time of day through HOV, which I think will be problematic down the line..

**Comment by jhelsel11** [comment]
@e-lo, Sijia and I had a file structure question we wanted to run by you.

Right now the lasso outputs don't really distinguish between general purpose and managed lanes once they're being written to the fixed width format that goes to cube. Both the general purpose link and the created ml link have the segment id, but the managed lane value is set to 0 since that is only being used to create log files. Would it make sense to you to add another field ("ml_flag" or "is_ml", etc.) to let me create logic that diverts between the managed and general purpose lanes? Right now, I think the only way to distinguish between them is to know that the managed lanes are the general purpose id + 1000000, which seems fragile. 

If you have any questions we can sketch the idea out tomorrow.

**Comment by e-lo** [comment]
This makes sense. Although...is there a way to flag it based on categories / access / price now?

**Comment by i-am-sijia** [comment]
> Although...is there a way to flag it based on categories / access / price now?

Yes, that's a way, for managed lanes, `access`  is `'all'`, and `segment_id` is 5 (in the example), and for general purpose lanes, `access` is `''`, and `segment_id` is 5.

**Comment by kulshresthaa** [comment]
> > Although...is there a way to flag it based on categories / access / price now?
> 
> Yes, that's a way, for managed lanes, `access` is `'all'`, and `segment_id` is 5 (in the example), and for general purpose lanes, `access` is `''`, and `segment_id` is 5.

`access` as "all" for managed lanes is temporary. I think this could away in future when not "all" the general purpose links have access/egress to managed lanes.

**Comment by jhelsel11** [comment]
Access seems like an unstable way to track this.

**Comment by i-am-sijia** [comment]
OK.  Let's create a variable to store ML flag, which would be 1 for only the ML.  @kulshresthaa can `ML` work?  I saw network wrangler is currently able to use `ML`, but drops it in the process.

**Comment by e-lo** [comment]
New variable will be "managed"

**Comment by kulshresthaa** [comment]
Done!
