### ISSUE TITLE
Problem installing lasso

### ISSUE THREAD

**Issue by jhelsel11** [wsp-sag/Lasso#69]
I tried to do a clean install of lasso and wrangler to make sure I could do that before I talk to Rachel tomorrow. I ran into a new issue and wasn't sure how to resolve it. Hoped you might have seen it (next comment).

If it's important, I'm on the develop branch for both network wrangler and lasso, installed the listed packages through conda-forge, and pip installed network wrangler by navigating to the network wrangler folder and `pip install -e .`

Do I need to be on master to install for some reason?

**Comment by jhelsel11** [comment]
I've pushed the error as a change to the project card (https://github.com/wsp-sag/Lasso/blob/develop/notebooks/Lasso%20Project%20Card%20Creation%20Quickstart.ipynb)

> ---------------------------------------------------------------------------
> ImportError                               Traceback (most recent call last)
> <ipython-input-1-1921aa916cde> in <module>
>       2 import sys
>       3 
> ----> 4 from lasso import Project
>       5 from lasso import CubeTransit
>       6 from network_wrangler import WranglerLogger
> 
> d:\wsp\lasso\lasso\__init__.py in <module>
>       1 __version__ = "0.0.0"
>       2 
> ----> 3 from .project import Project
>       4 from .transit import CubeTransit, StandardTransit
>       5 from .util import get_shared_streets_intersection_hash
> 
> d:\wsp\lasso\lasso\project.py in <module>
>       8 import geopandas as gpd
>       9 
> ---> 10 from network_wrangler import ProjectCard
>      11 from network_wrangler import RoadwayNetwork
>      12 
> 
> d:\wsp\network_wrangler\network_wrangler\__init__.py in <module>
>       6 from .projectcard import ProjectCard
>       7 from .roadwaynetwork import RoadwayNetwork
> ----> 8 from .transitnetwork import TransitNetwork
>       9 from .scenario import Scenario
>      10 from .utils import point_df_to_geojson, link_df_to_json, make_slug
> 
> d:\wsp\network_wrangler\network_wrangler\transitnetwork.py in <module>
>      12 import numpy as np
>      13 import pandas as pd
> ---> 14 import partridge as ptg
>      15 from partridge.config import default_config
>      16 
> 
> c:\users\jwalt\anaconda3\envs\lasso_env\lib\site-packages\partridge\__init__.py in <module>
>       1 from .__version__ import __version__
> ----> 2 from .readers import (
>       3     load_feed,
>       4     load_geo_feed,
>       5     load_raw_feed,
> 
> c:\users\jwalt\anaconda3\envs\lasso_env\lib\site-packages\partridge\readers.py in <module>
>      11 
>      12 from .config import default_config, geo_config, empty_config, reroot_graph
> ---> 13 from .gtfs import Feed
>      14 from .parsers import vparse_date
>      15 from .types import View
> 
> c:\users\jwalt\anaconda3\envs\lasso_env\lib\site-packages\partridge\gtfs.py in <module>
>       9 from .config import default_config
>      10 from .types import View
> ---> 11 from .utilities import detect_encoding, empty_df, setwrap
>      12 
>      13 
> 
> c:\users\jwalt\anaconda3\envs\lasso_env\lib\site-packages\partridge\utilities.py in <module>
>       1 from typing import Any, Dict, Iterable, Optional, Set, BinaryIO, Union
>       2 
> ----> 3 from cchardet import UniversalDetector
>       4 import networkx as nx
>       5 import numpy as np
> 
> c:\users\jwalt\anaconda3\envs\lasso_env\lib\site-packages\cchardet\__init__.py in <module>
> ----> 1 from cchardet import _cchardet
>       2 from .version import __version__
>       3 
>       4 
>       5 def detect(msg):
> 
> ImportError: DLL load failed: The specified module could not be found.

>

**Comment by jhelsel11** [comment]
Solved it by force updating cchardet through conda-forge.

**Comment by e-lo** [comment]
@jhelsel11 - can you update the README with info on how to do that if it is encountered?

Thanks for solving!

**Comment by jhelsel11** [comment]
Sure.

**Comment by jhelsel11** [comment]
I've updated the readme, but have been helping Rachel install network wrangler and lasso for the past 45 minutes. Will you take a look at whether conda install *package* gets the right package versions? We're having to reinstall half a dozen libraries using conda-forge to get the appropriate version (it's particularly breaking because pyproj 1.9.6 is throwing errors that then require a reinstall of geopandas off conda-forge).

**Comment by jhelsel11** [comment]
@rachelwikenmc asked to be tagged to this issue.
