### ISSUE TITLE
Test updated installation instructions on a clean environment

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/Lasso#77]
https://github.com/wsp-sag/Lasso/blob/develop/README.md

I tried them out on clean environments on my mac and they worked.

**Comment by jhelsel11** [comment]
The install works, however the scenario quick start crashed on me.

![image](https://user-images.githubusercontent.com/29383881/82585869-f1d3c580-9b53-11ea-89c7-37e11a6826d0.png)

2 other comments:

1) Will you add a clarification regarding the -e switch? If Rachel is working with lasso and you push a bug fix, will she need to reinstall the lasso environment if she doesn't use -e? Or will everything update in the background when she pulls the latest commit? (I told her that it would be best to install as -e but I'm not really sure.)

2) Do you think we should update the quickstarts to include a `validate=False` option? The scenario quick start fails right now even if everything is installed correctly.

**Comment by jhelsel11** [comment]
(I pushed the notebook with error in case that's more helpful.)
