### ISSUE TITLE
Update test data for csv and shp changes for create project

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/Lasso#83]
We didn't have tests for using csvs and shps as inputs to project card creations so I added them.  When doing so, I noticed that the changes that were specified in them were "calculated variables". Since we are trying to avoid creating the calculated variables unless necessary (especially for tests), they need to be updated with changes (they don't need to be "real") that use "regular fields" rather than calculated ones.

Files to update:

 - `example_csv_roadway_change.csv`  and   
 - `example_shapefile_roadway_change.shp`

**Comment by i-am-sijia** [comment]
Updated the test data.
