### ISSUE TITLE
SHP file check network compatibility doesn't work 

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/Lasso#84]
This bit of code doesn't work when the roadway changes come from a SHP file:
```python
link_changes_df = roadway_changes[
            (roadway_changes.OBJECT == "L")
            & (roadway_changes.OPERATION == "C")
        ]
```

Get following error: ` AttributeError: 'DataFrame' object has no attribute 'OBJECT'`

When running the test `test_shp_changes`

**Comment by i-am-sijia** [comment]
Updated test data.  "OBJECT" and "OPERATION" are required, otherwise Lasso doesn't know what to do with the input.

**Comment by jhelsel11** [comment]
Can this be closed?
