### ISSUE TITLE
Scenario Quickstart notebook osmnx errors

### ISSUE THREAD

**Issue by RachelWikenMC** [wsp-sag/Lasso#86]
trying to run the scenario creation quickstart notebook and getting OSMNX errors again. Very likely could be user error because i'm not following what this notebook is doing. I understand the concept, not following the scripts here. Need more explanation. 

The 2 code blocks under Create Base Scenario look the same, I don't understand why doing things twice? Also its pulling from NetworkWrangler and not the Lasso examples, so different files than in the project card creation notebook. I am not understanding what inputs I need to edit and what should be left alone. Would be helpful to have someone walk me through this. 

![image](https://user-images.githubusercontent.com/46349598/84924713-8a476200-b08e-11ea-97d8-5f6204369472.png)

@e-lo @jhelsel11 @DavidOry

**Comment by jhelsel11** [comment]
@RachelWikenMC

For your first question, the code block is unnecessarily repeated. I've deleted it and make a commit shortly.

For your second question, I'd be happy to walk you through. I have availability between 11:30-1 pacific this afternoon and any time after 11:30 tomorrow. I'd also suggest taking a look at scenario_1394E_managed_lanes.ipynb in the lasso notebook folder and the accompanying yaml file. (https://github.com/wsp-sag/client_met_council_network/blob/base_network_project_cards/data/interim/project_cards/settings/i394e_managed_lanes.yaml) I hope that helps give you a sense of what might need to be changed and what can be left alone.

**Comment by e-lo** [comment]
@RachelWikenMC  -  I got this issue yesterday for another project and was able to fairly quickly fix it. `osmnx` updated their API. Standby for a fix.

**Comment by e-lo** [comment]
Addressing in network wrangler in this issue: https://github.com/wsp-sag/network_wrangler/issues/185
