### ISSUE TITLE
GeoPandas Centroid Issue

### ISSUE THREAD

**Issue by DavidOry** [wsp-sag/Lasso#87]
`calculate_area_type` uses GeoPandas `centroid` method like this:

`centroids_gdf["geometry"] = centroids_gdf["geometry"].centroid`

When I run this as part of the Scenario Quickstart, `centroids_gdf["geometry"]` returns a pandas Series, not a GeoPandas DF, so the returned object cannot be used in subsequent spatial joins. Is this a recent change with GeoPandas? Or is the wrong version being used in the `develop` branch?

**Comment by e-lo** [comment]
Interesting. I just ran the test `test_calculate_area_type()` and `test_write_cube_roadway()` without trouble with the latest versions of `develop` branch and `geopandas==0.7.0`.  Do those tests pass for you?

I also ran the scenario quickstart notebook without problems (other than the bike plot issue)

**Comment by DavidOry** [comment]
Yes, must have been a problem with my configuration. Thanks.
