### ISSUE TITLE
unclear instructions for lasso_base_dir

### ISSUE THREAD

**Issue by jhelsel11** [wsp-sag/Lasso#89]
I moved my jupyter notebooks into the met council directory to try to clean my workflow up and have it all contained to one repo. When I try to run the scenario creation notebook, there's a step that fails because the notebook is no longer in the lasso directory.
```
model_road_net = ModelRoadwayNetwork.from_RoadwayNetwork(
    my_scenario.road_net, parameters=my_config.get("my_parameters", {})
)
```
I get the following message: 
```
"Cannot find Lasso base directory from {}, please input using keyword in parameters: `lasso_base_dir =` "
```

Can you tell me what the message means? Do I replace the my_config.get() call with a `{lasso_base_dir="D:\lasso"}`? Do I add a line in the my_parameters section of the configuration file and if so, what is the syntax and where should it go? I tried inserting lasso_base_dir as an argument in create_base_scenario, create_scenario, and from_RoadwayNetwork calls, but all of them rejected the argument as bad syntax.

**Comment by i-am-sijia** [comment]
add this to config yaml:

```
my_parameters:
    lasso_base_dir: "D:/lasso"           # or where your lasso directory is
```

**Comment by e-lo** [comment]
You can also feed in the directory when you run the code. Essentially anywhere that parameters is a keyword argument you can put `parameters = Parameters( lasso_base_dir =  "D:/lasso" )`

Why do you need this? because for operations using the `met_council_data` lasso needs to know where that is.

Todo (and I'll write an issue for this) is to reframe it around where the data is (which will make it more generalizable). 

cc: @DavidOry

**Comment by jhelsel11** [comment]
@i-am-sijia, in the example (https://github.com/wsp-sag/Lasso/blob/master/examples/settings/my_config.yaml) all of my_parameters has a "#" in front of the lines. Do I need to uncomment

```
my_parameters:
    lasso_base_dir: "D:/lasso"
```
or does the # have special meaning?

**Comment by i-am-sijia** [comment]
@jhelsel11 Those are just commented out because the default values are set in the parameter.py.  They were there probably during the code development stage, but now live as comment/example.

**Comment by jhelsel11** [comment]
@i-am-sijia, thanks.

@e-lo, I think we can close this issue? The generalizability problem has been moved to another place.

Feel free to reopen if I've misunderstood.
