### ISSUE TITLE
Crashing when opening log file- number of columns?

### ISSUE THREAD

**Issue by JonathanEhrlichMC** [wsp-sag/Lasso#93]
[no52.LOG](https://github.com/wsp-sag/Lasso/files/4968015/no52.LOG)

The following code:

```python
test_roadway_project = Project.create_project(
        base_roadway_dir=os.path.join(EX_DIR,"FullNet_72320"),
        roadway_log_file=os.path.join(EX_DIR,"FullNet_72320","no52.LOG"),
    )
```

gives the following error: (btw I counted and there are only 68 columns in the log file)

```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
c:\users\ehrlicjn\appdata\local\continuum\anaconda3\envs\lasso\lib\site-packages\pandas\core\internals\construction.py in _list_to_arrays(data, columns, coerce_float, dtype)
    496         result = _convert_object_array(
--> 497             content, columns, dtype=dtype, coerce_float=coerce_float
    498         )

c:\users\ehrlicjn\appdata\local\continuum\anaconda3\envs\lasso\lib\site-packages\pandas\core\internals\construction.py in _convert_object_array(content, columns, coerce_float, dtype)
    580             raise AssertionError(
--> 581                 f"{len(columns)} columns passed, passed data had "
    582                 f"{len(content)} columns"

AssertionError: 68 columns passed, passed data had 69 columns

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
<ipython-input-20-d07460f98171> in <module>
      1 test_roadway_project = Project.create_project(
      2         base_roadway_dir=os.path.join(EX_DIR,"FullNet_72320"),
----> 3         roadway_log_file=os.path.join(EX_DIR,"FullNet_72320","no52.LOG"),
      4     )
      5 

c:\users\ehrlicjn\documents\github\lasso\lasso\project.py in create_project(roadway_log_file, roadway_shp_file, roadway_csv_file, base_roadway_dir, base_transit_source, build_transit_source, roadway_changes, transit_changes, base_roadway_network, base_transit_network, build_transit_network, project_name, recalculate_calculated_variables, recalculate_distance, parameters)
    224             raise ValueError(msg)
    225         if roadway_log_file:
--> 226             roadway_changes = Project.read_logfile(roadway_log_file)
    227         elif roadway_shp_file:
    228             roadway_changes = gpd.read_file(roadway_shp_file)

c:\users\ehrlicjn\documents\github\lasso\lasso\project.py in read_logfile(logfilename)
    307 
    308         link_df = DataFrame(
--> 309             data=[re.split(",|;", x.replace("\"", "")) for x in LinkLines[1:]], columns=linkcol_names
    310         )
    311 

c:\users\ehrlicjn\appdata\local\continuum\anaconda3\envs\lasso\lib\site-packages\pandas\core\frame.py in __init__(self, data, index, columns, dtype, copy)
    472                     if is_named_tuple(data[0]) and columns is None:
    473                         columns = data[0]._fields
--> 474                     arrays, columns = to_arrays(data, columns, dtype=dtype)
    475                     columns = ensure_index(columns)
    476 

c:\users\ehrlicjn\appdata\local\continuum\anaconda3\envs\lasso\lib\site-packages\pandas\core\internals\construction.py in to_arrays(data, columns, coerce_float, dtype)
    459         return [], []  # columns if columns is not None else []
    460     if isinstance(data[0], (list, tuple)):
--> 461         return _list_to_arrays(data, columns, coerce_float=coerce_float, dtype=dtype)
    462     elif isinstance(data[0], abc.Mapping):
    463         return _list_of_dict_to_arrays(

c:\users\ehrlicjn\appdata\local\continuum\anaconda3\envs\lasso\lib\site-packages\pandas\core\internals\construction.py in _list_to_arrays(data, columns, coerce_float, dtype)
    498         )
    499     except AssertionError as e:
--> 500         raise ValueError(e) from e
    501     return result
    502 

ValueError: 68 columns passed, passed data had 69 columns
```

**Comment by JonathanEhrlichMC** [comment]
Also read the file in with pd.read_csv() and pandas thought it had 68 columns

**Comment by e-lo** [comment]
Problem seems to be with this line: 

https://github.com/wsp-sag/Lasso/blob/c74583e2d6b4a7b2304e49c92c37aefba9eae485/lasso/project.py#L308-L310

My quick guess is that the re statement is brittle and didn't hold up to some specifics in the log file.

@i-am-sijia can you check out since you wrote?

**Comment by JonathanEhrlichMC** [comment]
New error with different log file:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-f536499822c8> in <module>
      1 test_roadway_project = Project.create_project(
      2         base_roadway_dir=os.path.join(EX_DIR,"FullNet_72320"),
----> 3         roadway_log_file=os.path.join(EX_DIR,"FullNet_72320","randomtestedit.LOG"),
      4     )
      5 

c:\users\ehrlicjn\documents\github\lasso\lasso\project.py in create_project(roadway_log_file, roadway_shp_file, roadway_csv_file, base_roadway_dir, base_transit_source, build_transit_source, roadway_changes, transit_changes, base_roadway_network, base_transit_network, build_transit_network, project_name, recalculate_calculated_variables, recalculate_distance, parameters)
    251                 recalculate_calculated_variables = recalculate_calculated_variables,
    252                 recalculate_distance = recalculate_distance,
--> 253                 parameters = parameters,
    254             )
    255             base_roadway_network.split_properties_by_time_period_and_category()

c:\users\ehrlicjn\documents\github\lasso\lasso\roadway.py in read(link_file, node_file, shape_file, fast, recalculate_calculated_variables, recalculate_distance, parameters)
     78             road_net.links_df,
     79             road_net.shapes_df,
---> 80             parameters=parameters,
     81 
     82         )

c:\users\ehrlicjn\documents\github\lasso\lasso\roadway.py in __init__(self, nodes, links, shapes, parameters)
     38 
     39         # will have to change if want to alter them
---> 40         self.parameters = Parameters(**parameters)
     41 
     42         self.links_metcouncil_df = None

c:\users\ehrlicjn\documents\github\lasso\lasso\parameters.py in __init__(self, **kwargs)
    371             self.base_dir = get_base_dir(lasso_base_dir = kwargs.get("lasso_base_dir"))
    372         else:
--> 373             self.base_dir = get_base_dir()
    374 
    375         if 'data_file_location' in kwargs:

c:\users\ehrlicjn\documents\github\lasso\lasso\parameters.py in get_base_dir(lasso_base_dir)
     12     msg = "Cannot find Lasso base directory from {}, please input using keyword in parameters: `lasso_base_dir =` ".format(lasso_base_dir)
     13     WranglerLogger.error(msg)
---> 14     raise(ValueError(msg))
     15 
     16 

ValueError: Cannot find Lasso base directory from C:\Users\ehrlicjn\Desktop\NW_JE_Test\Notebook, please input using keyword in parameters: `lasso_base_dir =`

**Comment by i-am-sijia** [comment]
This is related to lasso directory setting in parameter, we have it in issue [89 ](https://github.com/wsp-sag/Lasso/issues/89) and [91](https://github.com/wsp-sag/Lasso/issues/91).  I guess you are running test outside of the lasso directory?  The temporary solution is adding this in lasso\examples\settings\my_config.yaml:

```
my_parameters:
    lasso_base_dir: "D:/lasso"           # or where your lasso directory is
```

We need to update the code to let user run lasso outside of lasso directory, and specify parameters freely in the notebook instead of config yaml.  @e-lo

**Comment by e-lo** [comment]
You don't need to use a config, you can address it at runtime. 

```python
my_parameters = lasso.Parameters(lasso_base_dir = YOUR_LASSO_DIRECTORY_HERE)

test_roadway_project = Project.create_project(
  base_roadway_dir=os.path.join(EX_DIR,"FullNet_72320"),
  roadway_log_file=os.path.join(EX_DIR,"FullNet_72320","randomtestedit.LOG")
  parameters = my_parameters
)
```

But I think we will adjust the API on this b/c it is confusing a lot of people. I have an open issue to address it: https://github.com/wsp-sag/Lasso/issues/92

**Comment by JonathanEhrlichMC** [comment]
my_parameters = lasso.Parameters(lasso_base_dir = EX_DIR)
​

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-14-c90befa39ac5> in <module>
----> 1 my_parameters = lasso.Parameters(lasso_base_dir = EX_DIR)

NameError: name 'lasso' is not defined


:


my_parameters = lasso.Parameters('c\\Users\\ehrlicjn\\Desktop\\NW_JE_Test')
​



---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-15-c61316a8548a> in <module>
----> 1 my_parameters = lasso.Parameters('c\\Users\\ehrlicjn\\Desktop\\NW_JE_Test')

NameError: name 'lasso' is not defined

**Comment by JonathanEhrlichMC** [comment]
Option 1 crashed lasso on import. Option 2 gave me a variety of syntax errors.

**Comment by e-lo** [comment]
@JonathanEhrlichMC I had an extra line in there before (you don't need to specify a variable `my_parameters` but I tested the above with. `parameters = {'lasso_base_dir' = YOUR_LASSO_DIRECTORY_HERE}` and it worked for me (and I wrote a test for it which is passing as well).  If you still get syntax errors please paste them. thx!

**Comment by e-lo** [comment]
Are you still having this issuee?

**Comment by JonathanEhrlichMC** [comment]
:


test_roadway_project = Project.create_project(
        base_roadway_dir=os.path.join(EX_DIR,"FullNet_72320"),
        roadway_log_file=os.path.join(EX_DIR,"FullNet_72320","randomtestedit.LOG"),
        parameters = {'lasso_base_dir' = 'c:\\Users\\ehrlicjn\\Documents\\GitHub\\lasso' }
    )
​
​



  File "<ipython-input-7-cee550ec4992>", line 4
    parameters = {'lasso_base_dir' = 'c:\\Users\\ehrlicjn\\Documents\\GitHub\\lasso' }
                                   ^
SyntaxError: invalid syntax

**Comment by e-lo** [comment]
Sorry, I mis-stated the dictionary syntax in the comment above. Dictionary assignment uses ":" rather than "="

`parameters = {'lasso_base_dir': 'c:\\Users\\ehrlicjn\\Documents\\GitHub\\lasso' }`

**Comment by JonathanEhrlichMC** [comment]
Now it's running!
