### ISSUE TITLE
cchardet / partridge import error

### ISSUE THREAD

**Issue by JonathanEhrlichMC** [wsp-sag/Lasso#95]
This suddenly started happening:

```python
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-c035408a02e4> in <module>
      2 import sys
      3 
----> 4 from lasso import Project
      5 from lasso import CubeTransit
      6 from network_wrangler import RoadwayNetwork

c:\users\ehrlicjn\documents\github\lasso\lasso\__init__.py in <module>
      1 __version__ = "0.0.0"
      2 
----> 3 from .project import Project
      4 from .transit import CubeTransit, StandardTransit
      5 from .util import get_shared_streets_intersection_hash

c:\users\ehrlicjn\documents\github\lasso\lasso\project.py in <module>
      9 import geopandas as gpd
     10 
---> 11 from network_wrangler import ProjectCard
     12 from network_wrangler import RoadwayNetwork
     13 

c:\users\ehrlicjn\documents\github\network_wrangler\network_wrangler\__init__.py in <module>
      8 from .projectcard import ProjectCard
      9 from .roadwaynetwork import RoadwayNetwork
---> 10 from .transitnetwork import TransitNetwork
     11 from .scenario import Scenario
     12 from .utils import point_df_to_geojson, link_df_to_json, make_slug

c:\users\ehrlicjn\documents\github\network_wrangler\network_wrangler\transitnetwork.py in <module>
     12 import numpy as np
     13 import pandas as pd
---> 14 import partridge as ptg
     15 from partridge.config import default_config
     16 

c:\users\ehrlicjn\appdata\local\continuum\anaconda3\envs\lasso\lib\site-packages\partridge\__init__.py in <module>
      1 from .__version__ import __version__
----> 2 from .readers import (
      3     load_feed,
      4     load_geo_feed,
      5     load_raw_feed,

c:\users\ehrlicjn\appdata\local\continuum\anaconda3\envs\lasso\lib\site-packages\partridge\readers.py in <module>
     11 
     12 from .config import default_config, geo_config, empty_config, reroot_graph
---> 13 from .gtfs import Feed
     14 from .parsers import vparse_date
     15 from .types import View

c:\users\ehrlicjn\appdata\local\continuum\anaconda3\envs\lasso\lib\site-packages\partridge\gtfs.py in <module>
      9 from .config import default_config
     10 from .types import View
---> 11 from .utilities import detect_encoding, empty_df, setwrap
     12 
     13 

c:\users\ehrlicjn\appdata\local\continuum\anaconda3\envs\lasso\lib\site-packages\partridge\utilities.py in <module>
      1 from typing import Any, Dict, Iterable, Optional, Set, BinaryIO, Union
      2 
----> 3 from cchardet import UniversalDetector
      4 import networkx as nx
      5 import numpy as np

c:\users\ehrlicjn\appdata\local\continuum\anaconda3\envs\lasso\lib\site-packages\cchardet\__init__.py in <module>
----> 1 from cchardet import _cchardet
      2 from .version import __version__
      3 
      4 
      5 def detect(msg):

ImportError: DLL load failed: The specified module could not be found.

```

**Comment by e-lo** [comment]
You are hitting all the jackpots!  

This is indicating that cchardet isn't installed correctly (it is one of "those libraries" which are notorious) but I have no earthly idea why you would just now be getting this error.

Usually cchardet should be installed with other packages.

`conda install -c conda-forge cchardet` in your terminal should fix it. If it is already installed try uninstalling and re-installing.

**Comment by JonathanEhrlichMC** [comment]
OSError                                   Traceback (most recent call last)
<ipython-input-3-c035408a02e4> in <module>
      2 import sys
      3 
----> 4 from lasso import Project
      5 from lasso import CubeTransit
      6 from network_wrangler import RoadwayNetwork

c:\users\ehrlicjn\documents\github\lasso\lasso\__init__.py in <module>
      1 __version__ = "0.0.0"
      2 
----> 3 from .project import Project
      4 from .transit import CubeTransit, StandardTransit
      5 from .util import get_shared_streets_intersection_hash

c:\users\ehrlicjn\documents\github\lasso\lasso\project.py in <module>
      9 import geopandas as gpd
     10 
---> 11 from network_wrangler import ProjectCard
     12 from network_wrangler import RoadwayNetwork
     13 

c:\users\ehrlicjn\documents\github\network_wrangler\network_wrangler\__init__.py in <module>
     39         "network_wrangler_{}.log".format(datetime.now().strftime("%Y-%m-%d_%H:%M:%S")),
     40     ),
---> 41     log_to_console=True,
     42 )

c:\users\ehrlicjn\documents\github\network_wrangler\network_wrangler\logger.py in setupLogging(level, log_filename, log_to_console)
     32 
     33     if log_filename:
---> 34         file_handler = logging.FileHandler(log_filename)
     35         file_handler.setLevel(logging.DEBUG)
     36         file_handler.setFormatter(FORMAT)

c:\users\ehrlicjn\appdata\local\continuum\anaconda3\envs\lasso\lib\logging\__init__.py in __init__(self, filename, mode, encoding, delay)
   1085             self.stream = None
   1086         else:
-> 1087             StreamHandler.__init__(self, self._open())
   1088 
   1089     def close(self):

c:\users\ehrlicjn\appdata\local\continuum\anaconda3\envs\lasso\lib\logging\__init__.py in _open(self)
   1114         Return the resulting stream.
   1115         """
-> 1116         return open(self.baseFilename, self.mode, encoding=self.encoding)
   1117 
   1118     def emit(self, record):

OSError: [Errno 22] Invalid argument: 'C:\\Users\\ehrlicjn\\Documents\\GitHub\\Lasso\\notebooks\\network_wrangler_2020-07-27_17:02:50.log'

**Comment by e-lo** [comment]
Bah humbug for window filename issues.  
I just pushed an update to network wrangler that makes the default logfile name something windows can probably deal with (although I don't have windows so please let me know if you run into same issue)

**Comment by JonathanEhrlichMC** [comment]
[condalistlasso.txt](https://github.com/wsp-sag/Lasso/files/4989301/condalistlasso.txt)
Is the fact that my installed package is called wrangler-lasso and not lasso relevant?

**Comment by JonathanEhrlichMC** [comment]
Works now!
